name: Provision and deploy

on:
    push:
      branches: [main]

    # workflow_run:
    #     workflows: ["Build Push nodejs"]
    #     types: completed
        

jobs:
    provision_deploy:
        # if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest

        steps:

            - name: checkout
              uses: actions/checkout@v4
              with:
                # ref: ""
                # path: ""
                sparse-checkout: "terraform"
                sparse-checkout-cone-mode: false

            - name: Configure AWS Credentials # not needed for tf, just passed those cred as env vars
              uses: aws-actions/configure-aws-credentials@v5.0.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: mv files to root $GITHUB_WORKSPACE
              run: |
                mv terraform/* .

            - name: initial terraform
              run: terraform init

            # - name: terraform plan
            #   run: terraform plan -no-color

            # - name: terraform apply
            #   run: terraform apply -auto-approve

            - name: terraform destroy
              run: terraform destroy -auto-approve